export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';
export const UPDATE_SINGLE_USER = 'UPDATE_SINGLE_USER';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const UPDATE_PRODUCT_VIEWS = 'UPDATE_PRODUCT_VIEWS';